
FOLDER = {}
FOLDER.ASSETS = "game/assets/"

MOUSE = {}
MOUSE.LEFT = "l"
MOUSE.RIGHT = "r"

DRAW_LAYER_TOP = -1
DRAW_LAYER_BOTTOM = 99999

LAYER_TYPE_NONE = 0
LAYER_TYPE_IMAGES = 1
LAYER_TYPE_BATCH = 2
LAYER_TYPE_BACKGROUND = 3